feeder: dataloader_video.BaseFeeder
phase: train
dataset: phoenix14
phoenix14_info: 
  dataset_root: ./dataset/phoenix2014/multisigner
  dict_path: ./preprocess/phoenix2014/gloss_dict.npy
  evaluation_dir: ./evaluation/slr_eval
  evaluation_prefix: phoenix2014-groundtruth

# dataset: phoenix14-si5
num_epoch: 80
work_dir: ./work_dir/stgcn_Bn_VAC_au_CCE10_W5/
load_checkpoints: ./work_dir/stgcn_Bn_VAC_au_CCE10_W5/dev_20.60_epoch57_model.pt
batch_size: 2
random_seed: 0
test_batch_size: 8
num_worker: 5
device: 0
use_ddp: False
use_tb: True
log_interval: 50
eval_interval: 1
save_interval: 5
# python in default
evaluate_tool: sclite


cce_activate_epoch: 10
loss_weights:
  SeqCTC: 1.0
  # VAC
  ConvCTC: 1.0
  Dist: 10.0
  CCELoss: 5.0
#load_weights: ''


optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [ 20, 35, 55]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0

model: slr_network.SLRModel
decode_mode: beam
model_args:
  hidden_size: 1024
  num_classes: 1296
  c2d_type: resnet18
  conv_type: 2
  use_bn: 1
  # SMKD
  share_classifier: False
  weight_norm: False
  stgcn_args:
    in_channels: 512
    out_channels: 1024
    t_kernel_size: 5
    edge_importance_weighting: True
    dropout: 0.5
    model: 'union'
